version: '3'
services:
  db:
    image: postgres:10
    container_name: pprv-db
    networks:
    - pprv
    environment:
      POSTGRES_DB: pprv_development
      POSTGRES_PASSWORD: rootpass
    ports:
    - 5432:5432

networks:
  pprv:
