default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  password: rootpass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pprv_development

test:
  <<: *default
  database: pprv_test

production:
  <<: *default
  host: <%= ENV['PPRV_DATABASE_HOST'] %>
  database: pprv_production
  username: <%= ENV['PPRV_DATABASE_USERNAME'] %>
  password: <%= ENV['PPRV_DATABASE_PASSWORD'] %>
